### ISSUE TITLE
Gradients become flat when too big?

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#15]
I've tweaked the blobs so that they have larger gradients. Here are the modified SVGs:
[blob.zip](https://github.com/poke1024/tove2d/files/2973364/blob.zip)

The blobs should look like this:
![2019-03-15-22:04:35](https://user-images.githubusercontent.com/23723605/54469440-5e904a80-476e-11e9-8669-5dd6dd96f6f0.png)

But they look like this instead:
![2019-03-15-22:03:43](https://user-images.githubusercontent.com/23723605/54469435-47e9f380-476e-11e9-9ef9-bb79edb6b561.png)

**Comment by pdesaulniers** [comment]
In case you prefer an example that uses the blobs demo:
[blob.zip](https://github.com/poke1024/tove2d/files/2973364/blob.zip)

The blobs look like this:
![2019-03-15-22:03:43](https://user-images.githubusercontent.com/23723605/54469435-47e9f380-476e-11e9-9ef9-bb79edb6b561.png)

Instead of something like this:
![2019-03-15-22:04:35](https://user-images.githubusercontent.com/23723605/54469440-5e904a80-476e-11e9-8669-5dd6dd96f6f0.png)

**Comment by poke1024** [comment]
This was indeed a precision problem.
