### ISSUE TITLE
"Best" quality gradient seems to handle alpha incorrectly

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#17]
Here's a modified svg from the gradients demo:
[gradients.svg.zip](https://github.com/poke1024/tove2d/files/2999336/gradients.svg.zip)

The "best" gradient should look like the "fast" one, but it doesn't:
![2019-03-23-08:33:07](https://user-images.githubusercontent.com/23723605/54866107-7b1c1c00-4d46-11e9-91d8-79398a9c4ac4.png)

_Originally posted by @pdesaulniers in https://github.com/poke1024/tove2d/issues/16#issuecomment-475866283_

**Comment by poke1024** [comment]
I've changed the gradients.svg in the demo to your version, as it's a good regression test for transparency and it also shows the banding in fast even better than my version.

**Comment by pdesaulniers** [comment]
Good! 

Also, it's interesting to see that the mesh renderer has slightly less apparent banding than the "best" texture in the demo, which I didn't expect.
