### ISSUE TITLE
"Best" quality texture still has some banding

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#19]
Related to https://github.com/poke1024/tove2d/issues/16

(I know that the README mentions that we shouldn't expect TÖVE to produce print quality vector renderings, but still, I figured it costs nothing to ask):

In the gradients demo, the "tex best" still has some visible banding when zoomed in.

Could there be an even higher quality texture mode, which has even less banding artifacts?

Personally, I wouldn't mind if it's somewhat slow, as I would use this for small flipbooks and static images.

Perhaps some additional dithering could be applied to the texture, after it has been generated? I don't know much about graphics programming, so I can't really propose any specific technique here... A naive approach could be to spread the pixels inside the shapes randomly as a post-processing step, though I'm not sure if that would look good...

Of course, feel free to close this issue if you think this should be left as-is. The current dithered texture looks already much, much better than the "fast" one. Besides, I suppose a lot of people won't notice the banding.

**Comment by poke1024** [comment]
The general saying with regard to banding is: "if all else fails, add noise". That's what I did now. You can also configure the amount of noise by using `graphics:setDisplay("texture", noise)` where `noise` is between 0 (no noise) and 1 (only noise). It also adds some noise by default now.

**Comment by pdesaulniers** [comment]
Great, I think it's a good approach. It can even be used creatively, to make textures look rough :)

I think the default noise value is a bit too high in the average case, though. I suppose the noise should be barely perceptible by default. 

It seems like very conservative amounts like 0.008 are good enough at reducing banding a little bit, without making the textures look noisy. It's not miraculous, but it helps a bit.

Anyway, I'm closing this issue. Thanks!

**Comment by pdesaulniers** [comment]
On a side note, I think this feature would be really great for creative purposes if we could apply it on a per-path basis, instead of applying it on the whole texture. 

I guess this could be done by looking for some custom attributes in the SVG's XML (such as "tove-noise"), but that doesn't seem like a great approach...

**Comment by poke1024** [comment]
@pdesaulniers I changed the noise API in the last commit. To specify custom noise, you now need to do: `graphics:setDisplay("texture", "best", "jarvis", 1, noise)` This was necessary to make everything logical in terms of the new retro modes.

A custom noise for per-path is a nice idea. I made myself a note (https://trello.com/b/p5nWCZVC/töve).

**Comment by pdesaulniers** [comment]
Cool!

By the way, I've tested the new blue noise dithering feature, and it seems like it's really great at reducing banding artifacts! I think it truly fixes the issue for me.
