### ISSUE TITLE
Error on building

### ISSUE THREAD

**Issue by welldoneconan** [poke1024/tove2d#2]
Hello

I used this instruction:

* Move "tovegd" into your godot /modules folder (i.e. as /modules/tovegd).
* Replace "tovegd/src" with the real tove2d src folder.
* Build godot using scons.

and got an error:

modules/tovegd/godot/vg_paint.h:8:10: fatal error: 'resource.h' file not found
#include "resource.h"

**Comment by poke1024** [comment]
@welldoneconan Builds now (tested with https://github.com/poke1024/tove2d/commit/c86e6bdede3597bfa7f442252ac8938d526745cc against current Godot master). Haven't worked on this for quite a while though. It's very experimental.

I've added some more docs here:

https://github.com/poke1024/tove2d/blob/master/godot/README.md

Drag and drop SVG import needs a patch.

**Comment by welldoneconan** [comment]
Thanks! Will try later

**Comment by welldoneconan** [comment]
Thanks!

Kostik Poloskin
FREELANCE GRAPHIC DESIGNER
+38 095 277 79 78
www.behance.net/welldoneconan
