### ISSUE TITLE
Latest release causes "Illegal instruction" error on Windows

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#24]
If I run the blob demo on Windows, using the latest v2.0a3 release, I get an `Illegal instruction` error. 

I also get this error in the latest git version, built using VS Community 2017.

I'm running Windows 10, 64-bit.

The v2.0a2 release does not have this issue.

**Comment by pdesaulniers** [comment]
Fixed by removing `/arch:AVX` from the SConstruct file.

I suppose this flag should be removed, for better hardware compatibility.

**Comment by poke1024** [comment]
@pdesaulniers No, AVX just makes some things considerably faster (esp. the dithering stuff in fact, where lots of pixel data is moved around). However, I haven't benchmarked this, so removing `/arch:AVX` is a good idea. I'll take care of it.

**Comment by pdesaulniers** [comment]
Actually, I'm getting the same error (SIGILL) on my low-end Linux laptop. 

In this case, the fix was to remove the `-mf16c` flag, and to tweak `common.h` so that it uses the non-instrinsic fp16 conversion.

**Comment by poke1024** [comment]
Ok, thanks a lot for debugging this. I'll change the defaults to not use this.
