### ISSUE TITLE
Remove a path / subpath from a graphics

### ISSUE THREAD

**Issue by nikki93** [poke1024/tove2d#30]
Unless I missed it -- it seems like there's no way to remove a `Path` or a `Subpath` from a `Graphics` other than to make a new `Graphics` that copies everything except that `Path` or `Subpath`? 🤔

**Comment by poke1024** [comment]
Finally fixed by https://github.com/poke1024/tove2d/commit/33cc2e203af2dc455f5df839aa9b4aa87f5bea26
