### ISSUE TITLE
Mention MSAA in the docs?

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#31]
At first, I thought the mesh renderer looked pretty pixelated. However, it looks much better if I set `t.window.msaa = 2` inside conf.lua:
```lua
function love.conf(t)
	t.window.msaa = 2
end
```
![2020-04-04-08:44:02](https://user-images.githubusercontent.com/23723605/78451313-e2a3c180-7652-11ea-880f-c0adaf0e72ed.png)

Perhaps this should be mentioned in the docs? Also, maybe this config variable should be added to the demos?

**Comment by poke1024** [comment]
Very good point. I should add that to the docs as well as to the demos.

**Comment by poke1024** [comment]
It's now in https://poke1024.github.io/tove2d/tutorials/Renderers/. Thanks for finding this!
