### ISSUE TITLE
Can Graphics be saved as svg files?

### ISSUE THREAD

**Issue by owlnical** [poke1024/tove2d#32]
Is it possible to save Graphics as text/svg? If so, how? I had a look in the docs but couldn't find anything.

Something like this :)

```lua
local tove = require "tove"
local myDrawing = tove.newGraphics()
myDrawing:moveTo(100, 100)
myDrawing:lineTo(200, 250)
myDrawing:lineTo(50, 220)
myDrawing:fill()

-- Save my drawing
local svg = myDrawing:save()
love.filesystem.write("myDrawing.svg", svg)
```

**Comment by poke1024** [comment]
No, not currently. There is a `Graphics:serialize()` function that returns a Lua table that can then be reinstantiated:

```
x = myGraphics:serialize()
local newInstance = tove.newGraphics(x)
```

This is used in the `editor` demo. But I'm not sure how well tested this is. It should basically work.

**Comment by owlnical** [comment]
Ok, thanks!
