### ISSUE TITLE
Color tween between SVGs?

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#9]
In the blob demo, if I change the color of gradient-circle_00002.svg (without changing gradient-circle_00001.svg), the color change is not visible in the demo. The animations only affect the shape of the object, not the color.

Is it currently possible to interpolate colors between SVG files in TOVE, without doing it "manually" in code? If not, would that be very complex to implement?

**Comment by poke1024** [comment]
Yes, as long as you stay in the same color type (e.g. "solid", "gradient with n colors") this is supposed to work. Will look into this.

**Comment by pdesaulniers** [comment]
Very cool! Thanks!
